# Generated by Django 2.2.11 on 2020-06-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokryvala', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokryvala',
            options={'verbose_name': 'Покрывала', 'verbose_name_plural': 'Покрывала'},
        ),
    ]
