# Generated by Django 2.2.11 on 2020-06-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0010_auto_20200413_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistDpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('product_name', models.CharField(blank=True, default=None, max_length=128, null=True, unique=True, verbose_name='Продукт')),
                ('size', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Размер')),
                ('slug', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Слаг')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('image', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Фото')),
                ('tkan', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Ткань')),
                ('brend', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Бренд')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Товар в жиланиях',
                'verbose_name_plural': 'Товары в жиланиях',
            },
        ),
    ]
