# Generated by Django 2.2.11 on 2020-05-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200413_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key_words',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Название'),
        ),
    ]
