# Generated by Django 2.2.11 on 2020-05-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_key_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Фотка ссылка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='key_words',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ключи'),
        ),
    ]
