# Generated by Django 2.2.11 on 2020-06-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odeyala', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odeyala',
            options={'verbose_name': 'Одеяла', 'verbose_name_plural': 'Одеяла'},
        ),
    ]
