# Generated by Django 2.2.11 on 2020-06-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pled', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pled',
            options={'verbose_name': 'Плед', 'verbose_name_plural': 'Плед'},
        ),
    ]
